SCREEN_TITLE = "Coffyc"
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1000

GAME_TITLE = "Coffyc"

CHARACTER_SCALING = 0.32
TILE_SCALING = 0.5
PLAYER_MOVEMENT_SPEED = 10
GRAVITY = 1
PLAYER_JUMP_SPEED = 20
ANIMATION_INTERVAL = 0.2

LEVEL_TIME_LIMITS = {
    0: 60,
    1: 50
}